services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: bloomingdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 5656
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: