spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bloomingdb}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:5656}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.blockchain.exchange: INFO